"""
Extraction functions for LLM responses produced by prompts defined in
prompt_list.py and prompt_list2.py.

Each function targets the exact output format described in its corresponding
prompt and returns a clean Python object (list, dict, bool, etc.).
"""

import re
import json
import ast
from typing import Optional


# ---------------------------------------------------------------------------
# prompt_list.py - system_prompt / user_prompt_template
# Output: Python list of three NL query strings, e.g.
#   ["Query 1?", "Query 2?", "Query 3?"]
# ---------------------------------------------------------------------------

def extract_nlg_queries(text: str) -> list[str]:
    """
    Extract the list of three natural-language paraphrases generated by
    ``system_prompt`` + ``user_prompt_template``.

    The LLM is instructed to return only a Python list literal, but may
    occasionally wrap it in a code fence.  We try ast.literal_eval first,
    then fall back to a regex scan.

    Returns a list of strings (may be empty on complete parse failure).
    """
    text = text.strip()

    # Strip markdown code fences if present
    fence_match = re.search(r"```(?:python)?\s*([\s\S]*?)```", text)
    if fence_match:
        text = fence_match.group(1).strip()

    # Try to parse a Python list literal directly
    try:
        result = ast.literal_eval(text)
        if isinstance(result, list):
            return [str(q) for q in result]
    except (ValueError, SyntaxError):
        pass

    # Fallback: extract strings between the outermost [ … ]
    bracket_match = re.search(r"\[([^\[\]]*(?:\"[^\"]*\"|'[^']*')[^\[\]]*)\]", text, re.DOTALL)
    if bracket_match:
        try:
            result = ast.literal_eval("[" + bracket_match.group(1) + "]")
            if isinstance(result, list):
                return [str(q) for q in result]
        except (ValueError, SyntaxError):
            pass

    # Last resort: collect all quoted strings in order
    queries = re.findall(r'"([^"]+)"|\'([^\']+)\'', text)
    return [a or b for a, b in queries]


# ---------------------------------------------------------------------------
# prompt_list.py - extract_relation_prompt / RELATION_EXTRACTION_SYSTEM_PROMPT
# Output lines (until <END>):
#   {relation/path (Score: 0.4)}: Explanation text
# ---------------------------------------------------------------------------

def extract_relations_with_scores(text: str) -> list[dict]:
    """
    Parse the output of ``extract_relation_prompt`` or
    ``RELATION_EXTRACTION_SYSTEM_PROMPT``.

    Each returned dict has keys:
        ``relation`` (str)  - full canonical relation name
        ``score``    (float) - relevance score 0.0 - 1.0
        ``explanation`` (str) - free-text explanation
    """
    # Truncate at <END> marker
    end_idx = text.find("<END>")
    if end_idx != -1:
        text = text[:end_idx]

    pattern = re.compile(
        r"\{([^(){}]+)\s+\(Score:\s*([0-9]*\.?[0-9]+)\)\}\s*:?\s*(.*?)(?=\{|$)",
        re.DOTALL,
    )

    results = []
    for match in pattern.finditer(text):
        relation = match.group(1).strip()
        try:
            score = float(match.group(2))
        except ValueError:
            score = 0.0
        explanation = match.group(3).strip().replace("\n", " ")
        results.append({"relation": relation, "score": score, "explanation": explanation})

    return results


# ---------------------------------------------------------------------------
# prompt_list.py - prompt_evaluate
# Output: {Yes} or {No}, optionally a second {answer} token
# ---------------------------------------------------------------------------

def extract_sufficiency_decision(text: str) -> dict:
    """
    Parse the output of ``prompt_evaluate``.

    Returns a dict with:
        ``is_sufficient`` (bool)
        ``answer``        (str | None) - extracted answer entity when {Yes}
        ``explanation``   (str)        - raw explanation text
    """
    # Look for {Yes} / {No} (case-insensitive)
    decision_match = re.search(r"\{(Yes|No)\}", text, re.IGNORECASE)
    is_sufficient = False
    if decision_match:
        is_sufficient = decision_match.group(1).lower() == "yes"

    # Extract the answer entity when present: {Some Answer}
    # Skip the first {Yes}/{No} token itself
    answer = None
    if is_sufficient:
        answer_matches = re.findall(r"\{([^{}]+)\}", text)
        # The first hit is "Yes"; the second (if any) is the actual answer
        content_answers = [m for m in answer_matches if m.lower() not in ("yes", "no")]
        if content_answers:
            answer = content_answers[-1].strip()

    # Strip trailing <END>
    explanation = text.replace("<END>", "").strip()

    return {
        "is_sufficient": is_sufficient,
        "answer": answer,
        "explanation": explanation,
    }


# ---------------------------------------------------------------------------
# prompt_list.py - subobjective_prompt
# Output: Python list of step strings
#   ['Step 1', 'Step 2', 'Step 3']
# ---------------------------------------------------------------------------

def extract_subobjectives(text: str) -> list[str]:
    """
    Parse the output of ``subobjective_prompt`` - a Python list of
    natural-language sub-task descriptions.

    Returns a list of strings (may be empty on parse failure).
    """
    text = text.strip()

    # Strip markdown code fences
    fence_match = re.search(r"```(?:python)?\s*([\s\S]*?)```", text)
    if fence_match:
        text = fence_match.group(1).strip()

    try:
        result = ast.literal_eval(text)
        if isinstance(result, list):
            return [str(s) for s in result]
    except (ValueError, SyntaxError):
        pass

    # Fallback: extract all quoted strings
    items = re.findall(r'"([^"]+)"|\'([^\']+)\'', text)
    return [a or b for a, b in items]


# ---------------------------------------------------------------------------
# prompt_list.py - subobjective_prompt2
# Output: Python list of relation/predicate names
#   ['located_in', 'has_calling_code']
# ---------------------------------------------------------------------------

def extract_relation_chain(text: str) -> list[str]:
    """
    Parse the output of ``subobjective_prompt2`` - an ordered list of
    knowledge-graph relation names required to answer the question.

    Returns a list of relation name strings.
    """
    return extract_subobjectives(text)  # identical output format


# ---------------------------------------------------------------------------
# prompt_list.py - score_entity_candidates_prompt
# Output first non-empty line: comma-separated float scores
#   0.0, 1.0, 0.0, 0.0
# ---------------------------------------------------------------------------

def extract_entity_scores(text: str, num_entities: Optional[int] = None) -> list[float]:
    """
    Parse the output of ``score_entity_candidates_prompt``.

    The LLM outputs scores as a comma-separated list on the first relevant
    line, followed by an explanation paragraph.

    Args:
        text:          Raw LLM response string.
        num_entities:  Expected number of scores; used to validate the parse.

    Returns:
        List of floats.  Falls back to uniform scores when parsing fails and
        ``num_entities`` was provided.
    """
    # Try to find a line that looks like comma-separated numbers
    for line in text.split("\n"):
        line = line.strip()
        tokens = re.split(r"[,\s]+", line)
        try:
            scores = [float(t) for t in tokens if t]
            if num_entities is None or len(scores) == num_entities:
                return scores
        except ValueError:
            continue

    # Fallback: all numbers in the text (in order of appearance)
    scores = [float(m) for m in re.findall(r"\b\d+(?:\.\d+)?\b", text)]
    if scores:
        if num_entities and len(scores) == num_entities:
            return scores
        if num_entities is None:
            return scores

    # Ultimate fallback: uniform distribution
    if num_entities:
        return [1.0 / num_entities] * num_entities
    return []


# ---------------------------------------------------------------------------
# prompt_list2.py - decision_prompt
# Output: JSON object
#   {
#     "strategic_reasoning": "...",
#     "contributory_relations": {
#       "existing": ["..."],
#       "missing":  ["..."]
#     }
#   }
# ---------------------------------------------------------------------------

def extract_decision_json(text: str) -> dict:
    """
    Parse the JSON object returned by ``decision_prompt``.

    Returns the parsed dict, or a partial dict with an ``_parse_error`` key
    if JSON decoding fails.

    Expected keys:
        ``strategic_reasoning``   (str)  - brief explanation of the reasoning step
        ``contributory_relations`` (dict) with:
            ``existing``  (list[int]) - IDs extracted from relations selected from the context
            ``missing``   (list[str]) - NL descriptions of relations absent from context
    """
    text = text.strip()

    # Strip markdown code fences
    fence_match = re.search(r"```(?:json)?\s*([\s\S]*?)```", text)
    if fence_match:
        text = fence_match.group(1).strip()

    result = None
    
    # Attempt direct JSON parse
    try:
        result = json.loads(text)
    except json.JSONDecodeError:
        # Try to locate the outermost JSON object
        brace_match = re.search(r"\{[\s\S]*\}", text)
        if brace_match:
            try:
                result = json.loads(brace_match.group(0))
            except json.JSONDecodeError:
                pass

    if result is None:
        return {
            "_parse_error": "Could not decode JSON from decision_prompt response.",
            "_raw": text,
        }

    # Extract IDs from existing relations (only for the existing array)
    if (isinstance(result, dict) and 
        "contributory_relations" in result and
        isinstance(result["contributory_relations"], dict) and 
        "existing" in result["contributory_relations"] and
        isinstance(result["contributory_relations"]["existing"], list)):
        
        existing_ids = []
        for item in result["contributory_relations"]["existing"]:
            if isinstance(item, str):
                # Extract ID (number before the colon)
                match = re.match(r"(\d+):", item)
                if match:
                    existing_ids.append(int(match.group(1)))
                else:
                    # If no colon pattern, keep the original item
                    existing_ids.append(item)
            else:
                existing_ids.append(str(item))
        
        result["contributory_relations"]["existing"] = existing_ids

    return result


# ---------------------------------------------------------------------------
# prompt_list2.py - entities_pruning_prompt
# Output: JSON list  ["ent_1", "ent_2", ..., "ent_k"]
# ---------------------------------------------------------------------------

def extract_pruned_entities(text: str) -> list[str]:
    """
    Parse the JSON list of entity names returned by ``entities_pruning_prompt``.

    Returns a list of entity name strings (may be empty on parse failure).
    """
    text = text.strip()

    # Strip markdown code fences
    fence_match = re.search(r"```(?:json)?\s*([\s\S]*?)```", text)
    if fence_match:
        text = fence_match.group(1).strip()

    # Direct JSON parse
    try:
        result = json.loads(text)
        if isinstance(result, list):
            return [str(e) for e in result]
    except json.JSONDecodeError:
        pass

    # Locate the first JSON array
    bracket_match = re.search(r"\[[\s\S]*?\]", text)
    if bracket_match:
        try:
            result = json.loads(bracket_match.group(0))
            if isinstance(result, list):
                return [str(e) for e in result]
        except json.JSONDecodeError:
            pass

    # Fallback: collect all quoted strings inside brackets
    items = re.findall(r'"([^"]+)"|\'([^\']+)\'', text)
    return [a or b for a, b in items]


# ---------------------------------------------------------------------------
# prompt_list2.py - GoG_answer_prompt
# Output: {YES}. Answer: ["entity_name"]   or   {NO}
# ---------------------------------------------------------------------------

def extract_gog_answer(text: str) -> dict:
    """
    Parse the output of ``GoG_answer_prompt``.

    Returns a dict with:
        ``found``    (bool)          True when the LLM answered {YES}
        ``entities`` (list[str])     answer entity names when found
        ``raw``      (str)           original response text
    """
    text_stripped = text.strip()

    found = bool(re.search(r"\{YES\}", text_stripped, re.IGNORECASE))

    entities: list[str] = []
    if found:
        # Try to extract the JSON list after "Answer:"
        answer_match = re.search(r"Answer\s*:\s*(\[[\s\S]*?\])", text_stripped, re.IGNORECASE)
        if answer_match:
            try:
                entities = json.loads(answer_match.group(1))
            except json.JSONDecodeError:
                # Fallback: grab quoted strings inside the brackets
                items = re.findall(r'"([^"]+)"|\'([^\']+)\'', answer_match.group(1))
                entities = [a or b for a, b in items]

    return {"found": found, "entities": entities, "raw": text_stripped}
